/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingFinanceRouteImport } from './routes/accounting-finance'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as HrRecruitmentRouteImport } from './routes/hr-recruitment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingFinanceRoute = AccountingFinanceRouteImport.update({
  id: '/accounting-finance',
  path: '/accounting-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRecruitmentRoute = HrRecruitmentRouteImport.update({
  id: '/hr-recruitment',
  path: '/hr-recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting-finance': typeof AccountingFinanceRoute
  '/employees': typeof EmployeesRoute
  '/hr-recruitment': typeof HrRecruitmentRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting-finance': typeof AccountingFinanceRoute
  '/employees': typeof EmployeesRoute
  '/hr-recruitment': typeof HrRecruitmentRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting-finance': typeof AccountingFinanceRoute
  '/employees': typeof EmployeesRoute
  '/hr-recruitment': typeof HrRecruitmentRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting-finance'
    | '/employees'
    | '/hr-recruitment'
    | '/login'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting-finance'
    | '/employees'
    | '/hr-recruitment'
    | '/login'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/accounting-finance'
    | '/employees'
    | '/hr-recruitment'
    | '/login'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingFinanceRoute: typeof AccountingFinanceRoute
  EmployeesRoute: typeof EmployeesRoute
  HrRecruitmentRoute: typeof HrRecruitmentRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-finance': {
      id: '/accounting-finance'
      path: '/accounting-finance'
      fullPath: '/accounting-finance'
      preLoaderRoute: typeof AccountingFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-recruitment': {
      id: '/hr-recruitment'
      path: '/hr-recruitment'
      fullPath: '/hr-recruitment'
      preLoaderRoute: typeof HrRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingFinanceRoute: AccountingFinanceRoute,
  EmployeesRoute: EmployeesRoute,
  HrRecruitmentRoute: HrRecruitmentRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
